version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: nextflix_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
