# Generated by Django 5.0.2 on 2024-03-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
    ]
