# Generated by Django 5.0.2 on 2024-03-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
