# Generated by Django 5.0.2 on 2024-03-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
