# Generated by Django 5.0.2 on 2024-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_thumbnail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.TextField(blank=True),
        ),
    ]
