# Generated by Django 5.0.2 on 2024-03-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_views_count_rating_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating_count',
        ),
    ]
